trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerRegistry: '<your-acr-service-connection>'  # Replace with your actual ACR service connection name
  acrName: '<your-acr-name>'  # Replace with your actual ACR name

stages:
- stage: TestACRLogin
  displayName: 'Test ACR Login'
  jobs:
  - job: TestLogin
    displayName: 'Verify ACR Authentication'
    steps:

    - script: echo "Testing Azure Container Registry Login..."
      displayName: 'Start ACR Login Test'

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: 'login'
        containerRegistry: $(containerRegistry)

    - script: |
        echo "Verifying ACR access..."
        az acr login --name $(acrName)
        echo "Listing repositories..."
        az acr repository list --name $(acrName) --output table
      displayName: 'Check ACR Repositories'
