trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'petclinic'

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    steps:

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSource: 'PreInstalled'
      displayName: 'Set Java 17'

    - script: java -version
      displayName: 'Verify Java Version'

    - task: MavenAuthenticate@0
      inputs:
        mavenServiceConnection: '<Your_Maven_Service_Connection_Name>'
        options: ''

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: true
        testResultsFiles: '**/target/surefire-reports/*.xml'

    - task: Docker@2
      inputs:
        containerRegistry: myContainerRegistryServiceConnection
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
        buildContext: '$(System.DefaultWorkingDirectory)/'
