trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'petclinic'
  containerRegistry: 'myContainerRegistryServiceConnection'

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    steps:

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
      displayName: 'Set Java 17'

    - script: java -version
      displayName: 'Verify Java Version'

    - task: MavenAuthenticate@0
      inputs:
        mavenServiceConnection: '<Your_Maven_Service_Connection_Name>'
        options: ''

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: true
        testResultsFiles: '**/target/surefire-reports/*.xml'

    - task: DockerCompose@0
      displayName: 'Build and Push Docker Images'
      inputs:
        containerRegistry: $(containerRegistry)
        dockerComposeFile: 'docker-compose.yml'
        action: 'BuildAndPush'
        additionalImageTags: |
          $(Build.BuildId)
